### ISSUE TITLE
Circuit breaker race condition

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-circuit-breaker#26]
```
Running io.vertx.circuitbreaker.impl.CircuitBreakerMetricsTest
Apr 05, 2018 10:39:30 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.AssertionError: 
Expecting:
 <1000>
to be less than:
 <1000> 
	at io.vertx.circuitbreaker.impl.CircuitBreakerMetricsTest.lambda$testEviction$6(CircuitBreakerMetricsTest.java:220)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.lambda$null$3(CircuitBreakerImpl.java:220)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by vietj** [comment]
still happening in CI : https://api.travis-ci.org/v3/job/438227052/log.txt

**Comment by cescoffier** [comment]
Fixed in master.
