### ISSUE TITLE
Deadlock in vertx event loop thread in class HystrixMetricEventStream

### ISSUE THREAD

**Issue by shubhhampagui** [vert-x3/vertx-circuit-breaker#54]
### Questions

Getting a deadlock in vertx event loop thread in class HystrixMetricEventStream

### Version

3.9.2

### Context

Following is the stack trace of the deadlock.

Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-33":
  waiting to lock monitor 0x00007fb2dc0ab5b8 (object 0x00000005decc1d00, a java.util.Collections$SynchronizedList),
  which is held by "vert.x-eventloop-thread-32"
"vert.x-eventloop-thread-32":
  waiting to lock monitor 0x00007fb5e40175c8 (object 0x00000006217cd9c8, a io.vertx.core.http.impl.Http1xServerConnection),
  which is held by "vert.x-eventloop-thread-33"

Java stack information for the threads listed above:
===================================================
"vert.x-eventloop-thread-33":
    at java.util.Collections$SynchronizedCollection.remove(Collections.java:2038)
    - waiting to lock <0x00000005decc1d00> (a java.util.Collections$SynchronizedList)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream.lambda$handle$3(HystrixMetricEventStream.java:114)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream$$Lambda$940/1263525672.handle(Unknown Source)
    at io.vertx.core.net.impl.ConnectionBase.handleException(ConnectionBase.java:332)
    - locked <0x00000006217cd9c8> (a io.vertx.core.http.impl.Http1xServerConnection)
    at io.vertx.core.http.impl.Http1xServerConnection.handleException(Http1xServerConnection.java:423)
    at io.vertx.core.net.impl.VertxHandler.lambda$exceptionCaught$3(VertxHandler.java:150)
    at io.vertx.core.net.impl.VertxHandler$$Lambda$922/107884447.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
    at io.vertx.core.net.impl.VertxHandler.exceptionCaught(VertxHandler.java:143)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:268)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1389)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:276)
    at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

`"vert.x-eventloop-thread-32":
    at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:677)
    - waiting to lock <0x00000006217cd9c8> (a io.vertx.core.http.impl.Http1xServerConnection)
    at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:325)
    at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:64)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream.lambda$null$0(HystrixMetricEventStream.java:39)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream$$Lambda$654/1232465312.accept(Unknown Source)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
    - locked <0x00000005decc1d00> (a java.util.Collections$SynchronizedList)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream.lambda$new$1(HystrixMetricEventStream.java:38)
    at io.vertx.circuitbreaker.impl.HystrixMetricEventStream$$Lambda$648/1196496258.handle(Unknown Source)
    at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:278)
    at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:264)
    at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)
    at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$4(EventBusImpl.java:533)
    at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$653/1091785879.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
    at io.vertx.core.impl.EventLoopContext$$Lambda$385/991402324.run(Unknown Source)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment]
I think the exception handler should not be called within the synchronized block

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/pull/4276

**Comment by shubhhampagui** [comment]
@vietj We are upgrading to vertx version 4.2.0. Is this issue fixed in that version?

**Comment by vietj** [comment]
no it should be 4.2.5
