### ISSUE TITLE
a java.lang.NullPointerException will be thrown when a null CircuitBreakerOptions is passed to CircuitBreaker.create

### ISSUE THREAD

**Issue by foxgem** [vert-x3/vertx-circuit-breaker#9]
CircuitBreaker.create(name, vertx, null) will throw the following exception:

~~~
java.lang.NullPointerException
	at io.vertx.circuitbreaker.impl.CircuitBreakerMetrics.<init>(CircuitBreakerMetrics.java:45)
	at io.vertx.circuitbreaker.impl.CircuitBreakerImpl.<init>(CircuitBreakerImpl.java:68)
~~~

After checking source code, in io.vertx.circuitbreaker.impl.CircuitBreakerImpl, the root cause is the following code in constructor and I marked it:

~~~
public CircuitBreakerImpl(String name, Vertx vertx, CircuitBreakerOptions options) {
    Objects.requireNonNull(name);
    Objects.requireNonNull(vertx);
    this.vertx = vertx;
    this.name = name;

    if (options == null) {
      this.options = new CircuitBreakerOptions();
    } else {
      this.options = new CircuitBreakerOptions(options);
    }

    this.metrics = new CircuitBreakerMetrics(vertx, this, options); <== should be this.options
~~~

For better coding, in io.vertx.circuitbreaker.CircuitBreaker:

~~~
static CircuitBreaker create(String name, Vertx vertx, CircuitBreakerOptions options) {
    return (options == null)? new CircuitBreakerImpl(name, vertx): new CircuitBreakerImpl(name, vertx, options);
 }
~~~

Thanks
Jian

**Comment by cescoffier** [comment]
Just fixed! thanks!
